Add new params to get applications endpoint and new properties to application body
perfect-flight/openapi pull request #4
Opened 2024-06-25 12:22 UTC by ViniciusContini

2024-07-01 11:09 UTC, throberto requested changes

2024-07-01 11:09 UTC, throberto commented on openapi.yaml
> +          description: unique farm identification
`finishedIn` = `unique farm identification` ?

2024-07-01 11:09 UTC, throberto commented on openapi.yaml
> +          description: unique farm identification
`startedIn` = `unique farm identification` ?

2024-07-01 13:26 UTC, ViniciusContini commented on openapi.yaml
> +          description: unique farm identification
Ajustado.

2024-07-01 13:26 UTC, ViniciusContini commented on openapi.yaml
> +          description: unique farm identification
Ajustado.

2024-07-01 13:26 UTC, ViniciusContini commented on openapi.yaml
> +          description: unique farm identification
Ajustado.

2024-07-08 11:32 UTC, EvandroCaslini approved these changes

2024-07-08 11:37 UTC, merged